const memes = [
  {
    name: "dr cuddy cat",
    img: "1house.jpg",
    desc: "cuddy as a cat. isn't this the best cat to pet? (yes)",
    type: "",
  },
  {
    name: "dr. freak",
    img: "2house.jpg",
    desc: "definetly pick up this call!",
    type: "",
  },
  {
    name: "papa louie: house md edition",
    img: "3house.jpg",
    desc: "i think this vexes me as well dr foreskin",
    type: "",
  },
  {
    name: "vicodin juggling",
    img: "4house.jpg",
    desc: "hes lockned n loaded when it comes to drug abuse",
    type: "",
  },
  {
    name: "chase and cat",
    img: "5house.jpg",
    desc: "me too me too dr chase im shocked too",
    type: "",
  },
  {
    name: "gay?",
    img: "6house.jpg",
    desc: "so are you or not?",
    type: "",
  },
  {
    name: "hilson brain connection",
    img: "7house.jpg",
    desc: "youre gonna live with these doctors this is normal for dr house and dr wilson",
    type: "",
  },
  {
    name: "taub fairy",
    img: "8house.jpg",
    desc: "hes so sweet and innocent i hope taub never bites the curb",
    type: "",
  },
  {
    name: "hilson couple counseling",
    img: "9house.jpg",
    desc: "cuddy does NOT wanna be with these two together",
    type: "",
  },
  {
    name: "dr wilson fish",
    img: "25house.jpg",
    desc: "i too am a fish on this website",
    type: "",
  },
  {
    name: "wilson smile",
    img: "10house.jpg",
    desc: "he's getting the facebook mom in. don't forget to smile!!",
    type: "",
  },
  {
    name: "wilson malewife",
    img: "11house.jpg",
    desc: "house and him are the og doomes yaoi",
    type: "",
  },
  {
    name: "foreman happy",
    img: "12house.jpg",
    desc: "buddy nothing can make you THIS happy youre a doctor for gosh sake",
    type: "",
  },
  {
    name: "foreman monday",
    img: "13house.jpg",
    desc: "keep calm and shoplift on",
    type: "",
  },
  {
    name: "all rounder house",
    img: "14house.jpg",
    desc: "at any given time he can be all of them",
    type: "",
  },
  {
    name: "crazy rejection",
    img: "15house.jpg",
    desc: "this is very fititng for the doomed yaoi they have",
    type: "",
  },
  {
    name: "flexible house",
    img: "16house.jpg",
    desc: "the amount of vicodin he would have to take to do this...",
    type: "",
  },
  {
    name: "",
    img: "",
    desc: "",
    type: "",
  },
  {
    name: "",
    img: "",
    desc: "",
    type: "",
  },
  {
    name: "",
    img: "",
    desc: "",
    type: "",
  },
  {
    name: "",
    img: "",
    desc: "",
    type: "",
  },
];
